title:              Brody's Website
email_1:            bbond@ncsu.edu           
email_2:            bond.brody.d@gmail.com            
description:        Howdy, folks!
author:             Brody Bond
baseurl:            ""
url:                "https://brodybond.github.io/"

# Social Profiles
github_username:    brodybond
linkedin_username:  bdbond

# Build settings
include:
  -img_galley
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
