title:              Brody Bond's Website
email_1:            bbond@ncsu.edu           
email_2:            bond.brody.d@gmail.com            
description:        Brody's Website
author:             Brody Bond
baseurl:            ""
url:                "https://brodybond.github.io/"

# Social Profiles
twitter_username:   
github_username:    brodybond
facebook_username:  
instagram_username:  
linkedin_username:

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
